<Calculadora>:
    cols: 1

    Label:
        text: root.display
        font_size: 40
        size_hint_y: 0.3

    GridLayout:
        cols: 4

        Button: 
            text: "7"
            on_press: root.agregar("7")

        Button: 
            text: "8"
            on_press: root.agregar("8")

        Button: 
            text: "9"
            on_press: root.agregar("9")

        Button: 
            text: "/"
            on_press: root.agregar("/")

        Button: 
            text: "4"
            on_press: root.agregar("4")

        Button: 
            text: "5"
            on_press: root.agregar("5")

        Button: 
            text: "6"
            on_press: root.agregar("6")

        Button: 
            text: "*"
            on_press: root.agregar("*")

        Button: 
            text: "1"
            on_press: root.agregar("1")

        Button: 
            text: "2"
            on_press: root.agregar("2")

        Button: 
            text: "3"
            on_press: root.agregar("3")

        Button
            text: "-"
            on_press: root.agregar("-")

        Button: 
            text: "0"
            on_press: root.agregar("0")

        Button: 
            text: "C"
            on_press: root.limpiar()

        Button: 
            text: "="
            on_press: root.calcular()

        Button: 
            text: "+"
            on_press: root.agregar("+")